# Generated by Django 4.2.9 on 2024-05-08 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0002_alter_slip_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('ตรวจสอบคำสั่งซื้อ', 'ตรวจสอบคำสั่งซื้อ'), ('กำลังจัดส่ง', 'กำลังจัดส่ง'), ('จัดส่งสำเร็จ', 'จัดส่งสำเร็จ'), ('คืนสินค้า', 'คืนสินค้า'), ('คืนสินค้าสำเร็จ', 'คืนสินค้าสำเร็จ')], max_length=20, null=True),
        ),
    ]
