# Generated by Django 4.2.9 on 2024-05-08 17:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0004_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='slip_image',
            field=models.ImageField(blank=True, null=True, upload_to='static/slips/'),
        ),
        migrations.AlterField(
            model_name='slip',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='slip', to='transport.order'),
        ),
    ]
