# Generated by Django 4.2.9 on 2024-05-14 06:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('buy', '0020_shippingaddress_orders'),
        ('transport', '0007_delete_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransportOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('courier', models.CharField(max_length=20, verbose_name=[('ไปรษณีย์ไทย', 'ไปรษณีย์ไทย'), ('Shopee express', 'Shopee express'), ('Kerry Express', 'Kerry Express'), ('BEST EXPRESS', 'BEST EXPRESS'), ('J&T EXPRESS', 'J&T EXPRESS'), ('FLASH EXPRESS', 'FLASH EXPRESS'), ('DHL EXPRESS', 'DHL EXPRESS')])),
                ('parcel_number', models.CharField(max_length=100)),
                ('delivery_status', models.CharField(max_length=100, verbose_name=[('กำลังจัดส่ง', 'กำลังจัดส่ง'), ('จัดส่งเสร็จสิ้น', 'จัดส่งเสร็จสิ้น')])),
                ('delivery_date', models.DateField(blank=True, null=True)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='buy.order')),
            ],
        ),
    ]
