# Generated by Django 4.2.9 on 2024-04-29 20:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sell', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Sale',
        ),
    ]
