# Generated by Django 4.2.9 on 2024-05-01 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='name',
            field=models.CharField(choices=[('Owner', 'Owner'), ('Customer', 'Customer'), ('Blocked', 'Blocked')], default='Customer', max_length=100),
        ),
    ]
