# Generated by Django 4.2.9 on 2024-05-09 17:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0023_alter_product_image1_alter_product_image2_and_more'),
        ('buy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('ตรวจสอบคำสั่งซื้อ', 'ตรวจสอบคำสั่งซื้อ'), ('กำลังจัดส่ง', 'กำลังจัดส่ง'), ('จัดส่งสำเร็จ', 'จัดส่งสำเร็จ'), ('คืนสินค้า', 'คืนสินค้า'), ('คืนสินค้าสำเร็จ', 'คืนสินค้าสำเร็จ')], default='ตรวจสอบคำสั่งซื้อ', max_length=20)),
                ('slip_image', models.ImageField(blank=True, null=True, upload_to='slips/')),
                ('cart_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='buy.cartitem')),
                ('product', models.ManyToManyField(to='posts.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
