# Generated by Django 4.2.9 on 2024-05-10 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buy', '0003_remove_order_cart_item_remove_order_product_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='order',
        ),
    ]
