# Generated by Django 4.2.9 on 2024-05-10 12:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('buy', '0004_remove_cartitem_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='user',
        ),
        migrations.AddField(
            model_name='order',
            name='cart',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='buy.cart'),
        ),
        migrations.AlterField(
            model_name='order',
            name='slip_image',
            field=models.ImageField(blank=True, null=True, upload_to='static/slips/'),
        ),
    ]
