# Generated by Django 4.2.9 on 2024-05-10 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buy', '0008_order_cart_items'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
