# Generated by Django 4.2.9 on 2024-05-12 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buy', '0009_order_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='status',
            field=models.CharField(choices=[('อยู่ในตะกร้า', 'อยู่ในตะกร้า'), ('กำลังชำระเงิน', 'กำลังชำระเงิน')], default='อยู่ในตะกร้า', max_length=20),
        ),
    ]
