# Generated by Django 4.2.9 on 2024-05-12 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buy', '0010_cartitem_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='items',
        ),
    ]
