# Generated by Django 4.2.9 on 2024-05-12 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buy', '0016_remove_cartitem_status_cart_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='status',
            field=models.CharField(choices=[('อยู่ในตะกร้า', 'อยู่ในตะกร้า'), ('ชำระเงินแล้ว', 'ชำระเงินแล้ว')], default='อยู่ในตะกร้า', max_length=20),
        ),
    ]
