# Generated by Django 4.2.9 on 2024-05-13 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buy', '0019_shippingaddress_firstname_shippingaddress_lastname'),
    ]

    operations = [
        migrations.AddField(
            model_name='shippingaddress',
            name='orders',
            field=models.ManyToManyField(related_name='shipping_addresses', to='buy.order'),
        ),
    ]
