# Generated by Django 4.2.9 on 2024-05-22 13:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0029_alter_notebook_camera'),
        ('buy', '0025_alter_shippingaddress_subswine'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='like',
            name='products',
        ),
        migrations.AddField(
            model_name='like',
            name='products',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='posts.product'),
        ),
    ]
