# Generated by Django 4.2.9 on 2024-05-22 13:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0029_alter_notebook_camera'),
        ('buy', '0026_remove_like_products_like_products'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='like',
            name='products',
        ),
        migrations.AddField(
            model_name='like',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='posts.product'),
        ),
    ]
