# Generated by Django 4.2.9 on 2024-05-25 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buy', '0027_remove_like_products_like_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='slip_image',
            field=models.ImageField(null=True, upload_to='static/slips/'),
        ),
    ]
