# Generated by Django 4.2.9 on 2024-05-25 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buy', '0028_alter_order_slip_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='slip_image',
            field=models.ImageField(blank=True, null=True, upload_to='static/slips/'),
        ),
    ]
