# Generated by Django 4.2.9 on 2024-04-16 20:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConnectivityDevices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=300)),
                ('description', models.TextField()),
                ('price', models.FloatField()),
                ('quantity', models.IntegerField()),
                ('image1', models.ImageField(upload_to='static/product_images/ConnectivityDevices/')),
                ('image2', models.ImageField(blank=True, upload_to='static/product_images/ConnectivityDevices/')),
                ('image3', models.ImageField(blank=True, upload_to='static/product_images/ConnectivityDevices/')),
                ('warranty', models.CharField(choices=[('1สัปดาห์', '1สัปดาห์'), ('2สัปดาห์', '1สัปดาห์'), ('3สัปดาห์', '1สัปดาห์'), ('1เดือน', '1เดือน'), ('2เดือน', '2เดือน'), ('3เดือน', '3เดือน'), ('4เดือน', '4เดือน'), ('5เดือน', '5เดือน'), ('6เดือน', '6เดือน')], max_length=8)),
                ('type', models.CharField(choices=[('Ethernet', 'สายแลน (Ethernet Cable)'), ('USB', 'สาย USB (USB Cable)'), ('HDMI', 'สาย HDMI (HDMI Cable)'), ('DVI', 'สาย DVI (DVI Cable)'), ('VGA', 'สาย VGA (VGA Cable)'), ('DisplayPort', 'สาย DisplayPort (DisplayPort Cable)'), ('Audio', 'สายออดิโอ (Audio Cable)'), ('Power', 'สายไฟ (Power Cable)')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Cpuseries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_series', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='HeadphoneSpeakers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(choices=[('Sennheiser', 'Sennheiser'), ('Sony', 'Sony'), ('Audio-Technica', 'Audio-Technica'), ('Bose', 'Bose'), ('JBL', 'JBL'), ('AKG', 'AKG'), ('Beyerdynamic', 'Beyerdynamic'), ('Beats by Dre', 'Beats by Dre'), ('SteelSeries', 'SteelSeries'), ('Skullcandy', 'Skullcandy'), ('Harman Kardon', 'Harman Kardon'), ('Marshall', 'Marshall'), ('Nubwo', 'Nubwo'), ('Sonos', 'Sonos'), ('Bang & Olufsen', 'Bang & Olufsen'), ('Logitech', 'Logitech'), ('Edifier', 'Edifier'), ('อื่นๆ', 'อื่นๆ')], max_length=50)),
                ('name', models.CharField(max_length=300)),
                ('description', models.TextField()),
                ('price', models.FloatField()),
                ('quantity', models.IntegerField()),
                ('image1', models.ImageField(upload_to='static/product_images/HeadphoneSpeakers/')),
                ('image2', models.ImageField(blank=True, upload_to='static/product_images/HeadphoneSpeakers/')),
                ('image3', models.ImageField(blank=True, upload_to='static/product_images/HeadphoneSpeakers/')),
                ('warranty', models.CharField(choices=[('1สัปดาห์', '1สัปดาห์'), ('2สัปดาห์', '1สัปดาห์'), ('3สัปดาห์', '1สัปดาห์'), ('1เดือน', '1เดือน'), ('2เดือน', '2เดือน'), ('3เดือน', '3เดือน'), ('4เดือน', '4เดือน'), ('5เดือน', '5เดือน'), ('6เดือน', '6เดือน')], max_length=8)),
                ('connect', models.CharField(choices=[('USB', 'USB'), ('Wireless', 'Wireless'), ('Bluetooth', 'Bluetooth'), ('Wireless Receiver', 'Wireless Receiver'), ('Thunderbolt', 'Thunderbolt'), ('Ethernet', 'Ethernet')], max_length=50)),
                ('size', models.CharField(choices=[('Small', 'Small'), ('Medium', 'Medium'), ('Medium', 'Medium')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Monitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(choices=[('HP', 'HP'), ('DELL', 'DELL'), ('ASUS', 'ASUS'), ('ACER', 'ACER'), ('LENOVO', 'LENOVO'), ('MSI', 'MSI'), ('VIEWSONIC', 'VIEWSONIC'), ('ZOWIE', 'ZOWIE'), ('APPLE', 'APPLE')], max_length=50)),
                ('name', models.CharField(max_length=300)),
                ('description', models.TextField()),
                ('price', models.FloatField()),
                ('quantity', models.IntegerField()),
                ('image1', models.ImageField(upload_to='static/product_images/Monitor/')),
                ('image2', models.ImageField(blank=True, upload_to='static/product_images/Monitor/')),
                ('image3', models.ImageField(blank=True, upload_to='static/product_images/Monitor/')),
                ('warranty', models.CharField(choices=[('1สัปดาห์', '1สัปดาห์'), ('2สัปดาห์', '1สัปดาห์'), ('3สัปดาห์', '1สัปดาห์'), ('1เดือน', '1เดือน'), ('2เดือน', '2เดือน'), ('3เดือน', '3เดือน'), ('4เดือน', '4เดือน'), ('5เดือน', '5เดือน'), ('6เดือน', '6เดือน')], max_length=8)),
                ('size', models.CharField(choices=[('14', '14'), ('15', '15'), ('16', '16'), ('17', '17'), ('18', '18'), ('19', '19'), ('21', '21'), ('23', '23'), ('24', '24'), ('27', '27'), ('30', '30'), ('32', '32'), ('34', '34')], max_length=50)),
                ('panel', models.CharField(choices=[('TN', 'TN'), ('VA', 'VA'), ('IPS', 'IPS'), ('OLED', 'OLED'), ('QLED', 'QLED')], max_length=50)),
                ('refresh_rate', models.CharField(choices=[('60Hz', '60Hz'), ('75Hz', '75Hz'), ('100Hz', '100Hz'), ('144Hz', '144Hz'), ('240Hz', '240Hz'), ('360Hz', '360Hz')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='MouseKeyboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(choices=[('Logitech', 'Logitech'), ('Razer', 'Razer'), ('SteelSeries', 'SteelSeries'), ('Corsair', 'Corsair'), ('ASUS', 'ASUS'), ('HP', 'HP'), ('Dell', 'Dell'), ('Microsoft', 'Microsoft'), ('Cooler Master', 'Cooler Master'), ('HyperX', 'HyperX'), ('Zowie', 'Zowie')], max_length=50)),
                ('name', models.CharField(max_length=300)),
                ('description', models.TextField()),
                ('price', models.FloatField()),
                ('quantity', models.IntegerField()),
                ('image1', models.ImageField(upload_to='static/product_images/MouseKeyboard/')),
                ('image2', models.ImageField(blank=True, upload_to='static/product_images/MouseKeyboard/')),
                ('image3', models.ImageField(blank=True, upload_to='static/product_images/MouseKeyboard/')),
                ('warranty', models.CharField(choices=[('1สัปดาห์', '1สัปดาห์'), ('2สัปดาห์', '1สัปดาห์'), ('3สัปดาห์', '1สัปดาห์'), ('1เดือน', '1เดือน'), ('2เดือน', '2เดือน'), ('3เดือน', '3เดือน'), ('4เดือน', '4เดือน'), ('5เดือน', '5เดือน'), ('6เดือน', '6เดือน')], max_length=8)),
                ('dpi', models.CharField(choices=[('office mouse 800-1600 DPI', 'office mouse 800-1600 DPI'), ('gaming mouse 2000-16000 DPI', 'gaming mouse 2000-16000 DPI')], max_length=50)),
                ('connect', models.CharField(choices=[('USB', 'USB'), ('Wireless', 'Wireless'), ('Bluetooth', 'Bluetooth'), ('Wireless Receiver', 'Wireless Receiver'), ('Thunderbolt', 'Thunderbolt'), ('Ethernet', 'Ethernet')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Printers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(choices=[('HP', 'HP'), ('Canon', 'Canon'), ('Epson', 'Epson'), ('Brother', 'Brother'), ('Samsung', 'Samsung'), ('Xerox', 'Xerox'), ('Kyocera', 'Kyocera')], max_length=50)),
                ('name', models.CharField(max_length=300)),
                ('description', models.TextField()),
                ('price', models.FloatField()),
                ('quantity', models.IntegerField()),
                ('image1', models.ImageField(upload_to='static/product_images/Printers/')),
                ('image2', models.ImageField(blank=True, upload_to='static/product_images/Printers/')),
                ('image3', models.ImageField(blank=True, upload_to='static/product_images/Printers/')),
                ('warranty', models.CharField(choices=[('1สัปดาห์', '1สัปดาห์'), ('2สัปดาห์', '1สัปดาห์'), ('3สัปดาห์', '1สัปดาห์'), ('1เดือน', '1เดือน'), ('2เดือน', '2เดือน'), ('3เดือน', '3เดือน'), ('4เดือน', '4เดือน'), ('5เดือน', '5เดือน'), ('6เดือน', '6เดือน')], max_length=8)),
                ('color', models.CharField(choices=[('Color', 'สี'), ('Monochrome', 'ขาว-ดำ'), ('Both', 'สีและขาว-ดำ')], max_length=50)),
                ('type_of_ink', models.CharField(choices=[('Inkjet', 'หมึกแทงค์ (Inkjet)'), ('Laser', 'เลเซอร์ (Laser)'), ('Dot Matrix', 'ดอทเมทริกซ์ (Dot Matrix)'), ('Thermal', 'เทอร์มัล (Thermal)'), ('Solid Ink', 'หมึกแข็ง (Solid Ink)'), ('Dye Sublimation', 'ไดซับลิเมชัน (Dye Sublimation)')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ProductType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='SDCards_USBs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=300)),
                ('price', models.FloatField()),
                ('quantity', models.IntegerField()),
                ('image1', models.ImageField(upload_to='static/product_images/SDCards_USBs/')),
                ('image2', models.ImageField(blank=True, upload_to='static/product_images/SDCards_USBs/')),
                ('image3', models.ImageField(blank=True, upload_to='static/product_images/SDCards_USBs/')),
                ('warranty', models.CharField(choices=[('1สัปดาห์', '1สัปดาห์'), ('2สัปดาห์', '1สัปดาห์'), ('3สัปดาห์', '1สัปดาห์'), ('1เดือน', '1เดือน'), ('2เดือน', '2เดือน'), ('3เดือน', '3เดือน'), ('4เดือน', '4เดือน'), ('5เดือน', '5เดือน'), ('6เดือน', '6เดือน')], max_length=8)),
                ('capacity', models.CharField(choices=[('4GB', '4GB'), ('8GB', '8GB'), ('16GB', '16GB'), ('32GB', '32GB'), ('64GB', '64GB'), ('128GB', '128GB'), ('256GB', '256GB')], max_length=10)),
                ('speed', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts.producttype')),
            ],
        ),
        migrations.CreateModel(
            name='Notebook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(choices=[('HP', 'HP'), ('DELL', 'DELL'), ('ASUS', 'ASUS'), ('ACER', 'ACER'), ('LENOVO', 'LENOVO'), ('MSI', 'MSI'), ('APPLE', 'APPLE')], max_length=50)),
                ('name', models.CharField(max_length=300)),
                ('description', models.TextField()),
                ('price', models.FloatField()),
                ('quantity', models.IntegerField()),
                ('image1', models.ImageField(upload_to='static/product_images/notebook/')),
                ('image2', models.ImageField(blank=True, upload_to='static/product_images/notebook/')),
                ('image3', models.ImageField(blank=True, upload_to='static/product_images/notebook/')),
                ('wwarranty', models.CharField(choices=[('1สัปดาห์', '1สัปดาห์'), ('2สัปดาห์', '1สัปดาห์'), ('3สัปดาห์', '1สัปดาห์'), ('1เดือน', '1เดือน'), ('2เดือน', '2เดือน'), ('3เดือน', '3เดือน'), ('4เดือน', '4เดือน'), ('5เดือน', '5เดือน'), ('6เดือน', '6เดือน')], max_length=8)),
                ('accessorise', models.CharField(max_length=300)),
                ('cpu_band', models.CharField(choices=[('INTEL', 'INTEL'), ('AMD', 'AMD')], max_length=50)),
                ('cpu_gen', models.CharField(choices=[('CELERON', 'CELERON'), ('PENTIUM', 'PENTIUM'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10'), ('11', '11'), ('12', '12'), ('13', '13'), ('14', '14'), ('15', '15'), ('16', '16'), ('RYZEN 3', 'RYZEN 3'), ('RYZEN 5', 'RYZEN 5'), ('RYZEN 7', 'RYZEN 7'), ('RYZEN 9', 'RYZEN 9')], max_length=50)),
                ('ram', models.CharField(choices=[('2', '2'), ('4', '4'), ('6', '6'), ('8', '8'), ('10', '10'), ('12', '12'), ('14', '14'), ('16', '16'), ('18', '18'), ('20', '20')], max_length=50)),
                ('rom', models.CharField(choices=[('128', '128'), ('256', '256'), ('512', '512'), ('1TB', '1TB'), ('2TB', '2TB'), ('3TB', '3TB'), ('4TB', '4TB'), ('5TB', '5TB')], max_length=50)),
                ('gpu', models.CharField(max_length=100)),
                ('system', models.CharField(choices=[('WINDOW', 'WINDOW'), ('IOS', 'IOS')], max_length=50)),
                ('cpu_series', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts.cpuseries')),
            ],
        ),
        migrations.CreateModel(
            name='Computer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(choices=[('HP', 'HP'), ('DELL', 'DELL'), ('ASUS', 'ASUS'), ('ACER', 'ACER'), ('LENOVO', 'LENOVO'), ('MSI', 'MSI'), ('APPLE', 'APPLE')], max_length=50)),
                ('name', models.CharField(max_length=300)),
                ('description', models.TextField()),
                ('price', models.FloatField()),
                ('quantity', models.IntegerField()),
                ('image1', models.ImageField(upload_to='static/product_images/computer/')),
                ('image2', models.ImageField(blank=True, upload_to='static/product_images/computer/')),
                ('image3', models.ImageField(blank=True, upload_to='static/product_images/computer/')),
                ('warranty', models.CharField(choices=[('1สัปดาห์', '1สัปดาห์'), ('2สัปดาห์', '1สัปดาห์'), ('3สัปดาห์', '1สัปดาห์'), ('1เดือน', '1เดือน'), ('2เดือน', '2เดือน'), ('3เดือน', '3เดือน'), ('4เดือน', '4เดือน'), ('5เดือน', '5เดือน'), ('6เดือน', '6เดือน')], max_length=8)),
                ('accessorise', models.CharField(max_length=300)),
                ('cpu_band', models.CharField(choices=[('INTEL', 'INTEL'), ('AMD', 'AMD')], max_length=50)),
                ('cpu_gen', models.CharField(choices=[('CELERON', 'CELERON'), ('PENTIUM', 'PENTIUM'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10'), ('11', '11'), ('12', '12'), ('13', '13'), ('14', '14'), ('15', '15'), ('16', '16'), ('RYZEN 3', 'RYZEN 3'), ('RYZEN 5', 'RYZEN 5'), ('RYZEN 7', 'RYZEN 7'), ('RYZEN 9', 'RYZEN 9')], max_length=50)),
                ('ram', models.CharField(choices=[('2', '2'), ('4', '4'), ('6', '6'), ('8', '8'), ('10', '10'), ('12', '12'), ('14', '14'), ('16', '16'), ('18', '18'), ('20', '20')], max_length=50)),
                ('rom', models.CharField(choices=[('128', '128'), ('256', '256'), ('512', '512'), ('1TB', '1TB'), ('2TB', '2TB'), ('3TB', '3TB'), ('4TB', '4TB'), ('5TB', '5TB')], max_length=50)),
                ('gpu', models.CharField(max_length=100)),
                ('system', models.CharField(choices=[('WINDOW', 'WINDOW'), ('IOS', 'IOS')], max_length=50)),
                ('cpu_series', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts.cpuseries')),
            ],
        ),
    ]
