# Generated by Django 4.2.9 on 2024-04-16 20:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_computer_product_connectivitydevices_product_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='computer',
            name='product',
        ),
        migrations.RemoveField(
            model_name='connectivitydevices',
            name='product',
        ),
        migrations.RemoveField(
            model_name='headphonespeakers',
            name='product',
        ),
        migrations.RemoveField(
            model_name='monitor',
            name='product',
        ),
        migrations.RemoveField(
            model_name='mousekeyboard',
            name='product',
        ),
        migrations.RemoveField(
            model_name='notebook',
            name='product',
        ),
        migrations.RemoveField(
            model_name='printers',
            name='product',
        ),
        migrations.RemoveField(
            model_name='sdcards_usbs',
            name='product',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.DeleteModel(
            name='ProductType',
        ),
    ]
