# Generated by Django 4.2.9 on 2024-04-16 20:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_remove_computer_product_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts.producttype')),
            ],
        ),
        migrations.AddField(
            model_name='computer',
            name='product',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='posts.product'),
        ),
        migrations.AddField(
            model_name='connectivitydevices',
            name='product',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='posts.product'),
        ),
        migrations.AddField(
            model_name='headphonespeakers',
            name='product',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='posts.product'),
        ),
        migrations.AddField(
            model_name='monitor',
            name='product',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='posts.product'),
        ),
        migrations.AddField(
            model_name='mousekeyboard',
            name='product',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='posts.product'),
        ),
        migrations.AddField(
            model_name='notebook',
            name='product',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='posts.product'),
        ),
        migrations.AddField(
            model_name='printers',
            name='product',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='posts.product'),
        ),
        migrations.AddField(
            model_name='sdcards_usbs',
            name='product',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='posts.product'),
        ),
    ]
