# Generated by Django 4.2.9 on 2024-04-20 15:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_remove_computer_product_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='computer',
            name='warranty',
            field=models.CharField(choices=[('1สัปดาห์', '1สัปดาห์'), ('2สัปดาห์', '2สัปดาห์'), ('3สัปดาห์', '3สัปดาห์'), ('1เดือน', '1เดือน'), ('2เดือน', '2เดือน'), ('3เดือน', '3เดือน'), ('4เดือน', '4เดือน'), ('5เดือน', '5เดือน'), ('6เดือน', '6เดือน')], max_length=8),
        ),
        migrations.AlterField(
            model_name='connectivitydevices',
            name='warranty',
            field=models.CharField(choices=[('1สัปดาห์', '1สัปดาห์'), ('2สัปดาห์', '2สัปดาห์'), ('3สัปดาห์', '3สัปดาห์'), ('1เดือน', '1เดือน'), ('2เดือน', '2เดือน'), ('3เดือน', '3เดือน'), ('4เดือน', '4เดือน'), ('5เดือน', '5เดือน'), ('6เดือน', '6เดือน')], max_length=8),
        ),
        migrations.AlterField(
            model_name='headphonespeakers',
            name='warranty',
            field=models.CharField(choices=[('1สัปดาห์', '1สัปดาห์'), ('2สัปดาห์', '2สัปดาห์'), ('3สัปดาห์', '3สัปดาห์'), ('1เดือน', '1เดือน'), ('2เดือน', '2เดือน'), ('3เดือน', '3เดือน'), ('4เดือน', '4เดือน'), ('5เดือน', '5เดือน'), ('6เดือน', '6เดือน')], max_length=8),
        ),
        migrations.AlterField(
            model_name='monitor',
            name='warranty',
            field=models.CharField(choices=[('1สัปดาห์', '1สัปดาห์'), ('2สัปดาห์', '2สัปดาห์'), ('3สัปดาห์', '3สัปดาห์'), ('1เดือน', '1เดือน'), ('2เดือน', '2เดือน'), ('3เดือน', '3เดือน'), ('4เดือน', '4เดือน'), ('5เดือน', '5เดือน'), ('6เดือน', '6เดือน')], max_length=8),
        ),
        migrations.AlterField(
            model_name='mousekeyboard',
            name='warranty',
            field=models.CharField(choices=[('1สัปดาห์', '1สัปดาห์'), ('2สัปดาห์', '2สัปดาห์'), ('3สัปดาห์', '3สัปดาห์'), ('1เดือน', '1เดือน'), ('2เดือน', '2เดือน'), ('3เดือน', '3เดือน'), ('4เดือน', '4เดือน'), ('5เดือน', '5เดือน'), ('6เดือน', '6เดือน')], max_length=8),
        ),
        migrations.AlterField(
            model_name='notebook',
            name='wwarranty',
            field=models.CharField(choices=[('1สัปดาห์', '1สัปดาห์'), ('2สัปดาห์', '2สัปดาห์'), ('3สัปดาห์', '3สัปดาห์'), ('1เดือน', '1เดือน'), ('2เดือน', '2เดือน'), ('3เดือน', '3เดือน'), ('4เดือน', '4เดือน'), ('5เดือน', '5เดือน'), ('6เดือน', '6เดือน')], max_length=8),
        ),
        migrations.AlterField(
            model_name='printers',
            name='warranty',
            field=models.CharField(choices=[('1สัปดาห์', '1สัปดาห์'), ('2สัปดาห์', '2สัปดาห์'), ('3สัปดาห์', '3สัปดาห์'), ('1เดือน', '1เดือน'), ('2เดือน', '2เดือน'), ('3เดือน', '3เดือน'), ('4เดือน', '4เดือน'), ('5เดือน', '5เดือน'), ('6เดือน', '6เดือน')], max_length=8),
        ),
        migrations.AlterField(
            model_name='sdcards_usbs',
            name='warranty',
            field=models.CharField(choices=[('1สัปดาห์', '1สัปดาห์'), ('2สัปดาห์', '2สัปดาห์'), ('3สัปดาห์', '3สัปดาห์'), ('1เดือน', '1เดือน'), ('2เดือน', '2เดือน'), ('3เดือน', '3เดือน'), ('4เดือน', '4เดือน'), ('5เดือน', '5เดือน'), ('6เดือน', '6เดือน')], max_length=8),
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts.producttype')),
            ],
        ),
        migrations.AddField(
            model_name='computer',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='posts.product'),
        ),
    ]
