# Generated by Django 4.2.9 on 2024-04-27 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0009_rename_product_computer_product_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='computer',
            old_name='product_id',
            new_name='product',
        ),
        migrations.RenameField(
            model_name='connectivitydevices',
            old_name='product_id',
            new_name='product',
        ),
        migrations.RenameField(
            model_name='headphonespeakers',
            old_name='product_id',
            new_name='product',
        ),
        migrations.RenameField(
            model_name='monitor',
            old_name='product_id',
            new_name='product',
        ),
        migrations.RenameField(
            model_name='mousekeyboard',
            old_name='product_id',
            new_name='product',
        ),
        migrations.RenameField(
            model_name='notebook',
            old_name='product_id',
            new_name='product',
        ),
        migrations.RenameField(
            model_name='printers',
            old_name='product_id',
            new_name='product',
        ),
        migrations.RenameField(
            model_name='sdcards_usbs',
            old_name='product_id',
            new_name='product',
        ),
    ]
