# Generated by Django 4.2.9 on 2024-04-29 20:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0010_rename_product_id_computer_product_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='computer',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='posts.product'),
        ),
        migrations.AlterField(
            model_name='connectivitydevices',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='posts.product'),
        ),
        migrations.AlterField(
            model_name='headphonespeakers',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='posts.product'),
        ),
        migrations.AlterField(
            model_name='monitor',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='posts.product'),
        ),
        migrations.AlterField(
            model_name='mousekeyboard',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='posts.product'),
        ),
        migrations.AlterField(
            model_name='notebook',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='posts.product'),
        ),
        migrations.AlterField(
            model_name='printers',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='posts.product'),
        ),
        migrations.AlterField(
            model_name='sdcards_usbs',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='posts.product'),
        ),
    ]
