# Generated by Django 4.2.9 on 2024-04-30 19:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0011_alter_computer_product_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='computer',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='computer', to='posts.product'),
        ),
    ]
