# Generated by Django 4.2.9 on 2024-04-30 20:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0017_alter_computer_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='connectivitydevices',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='connectivitydevices', to='posts.product'),
        ),
        migrations.AlterField(
            model_name='headphonespeakers',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='headphonespeakers', to='posts.product'),
        ),
        migrations.AlterField(
            model_name='monitor',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='monitor', to='posts.product'),
        ),
        migrations.AlterField(
            model_name='notebook',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notebook', to='posts.product'),
        ),
        migrations.AlterField(
            model_name='sdcards_usbs',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sdcards_usbs', to='posts.product'),
        ),
    ]
