# Generated by Django 4.2.9 on 2024-04-30 20:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0018_alter_connectivitydevices_product_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='printers',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='printers', to='posts.product'),
        ),
    ]
