# Generated by Django 4.2.9 on 2024-05-01 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0020_alter_connectivitydevices_product_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='computer',
            name='mainboard',
            field=models.CharField(default='default_value', max_length=300),
        ),
        migrations.AddField(
            model_name='computer',
            name='powersupply',
            field=models.CharField(default='default_value', max_length=300),
        ),
        migrations.AddField(
            model_name='notebook',
            name='camera',
            field=models.CharField(choices=[('NO', 'NO'), ('YES', 'YES')], default='default_value', max_length=50),
        ),
        migrations.AddField(
            model_name='notebook',
            name='display',
            field=models.CharField(choices=[('13.3', '13.3'), ('14.0', '14.0'), ('15.6', '15.6'), ('16.0', '16.0'), ('17.3', '17.3')], default='default_value', max_length=50),
        ),
        migrations.AlterField(
            model_name='computer',
            name='cpu_band',
            field=models.CharField(choices=[('INTEL', 'INTEL'), ('AMD', 'AMD'), ('APPLE', 'APPLE')], max_length=50),
        ),
        migrations.AlterField(
            model_name='computer',
            name='cpu_gen',
            field=models.CharField(choices=[('CELERON', 'CELERON'), ('PENTIUM', 'PENTIUM'), ('I3', 'I3'), ('I5', 'I5'), ('I7', 'I7'), ('I9', 'I9'), ('RYZEN 3', 'RYZEN 3'), ('RYZEN 5', 'RYZEN 5'), ('RYZEN 7', 'RYZEN 7'), ('RYZEN 9', 'RYZEN 9'), ('M1', 'M1'), ('M1 Pro', 'M1 Pro'), ('M1 Max', 'M1 Max'), ('M2', 'M2'), ('M2 Pro', 'M2 Pro'), ('M2 Max', 'M2 Max'), ('M3', 'M3'), ('M3 Pro', 'M3 Pro'), ('M3 Max', 'M3 Max')], max_length=50),
        ),
        migrations.AlterField(
            model_name='computer',
            name='rom',
            field=models.CharField(choices=[('128GB HHD', '128GB HHD'), ('256GB HHD', '256GB HHD'), ('512GB HHD', '512GB HHD'), ('1TB HHD', '1TB HHD'), ('2TB HHD', '2TB HHD'), ('3TB HHD', '3TB HHD'), ('4TB HHD', '4TB HHD'), ('5TB HHD', '5TB HHD'), ('128GB SSD', '128GB SSD'), ('256GB SSD', '256GB SSD'), ('512GB SSD', '512GB SSD'), ('1TB SSD', '1TB SSD'), ('2TB SSD', '2TB SSD'), ('3TB SSD', '3TB SSD'), ('4TB SSD', '4TB SSD'), ('5TB SSD', '5TB SSD')], max_length=50),
        ),
        migrations.AlterField(
            model_name='mousekeyboard',
            name='dpi',
            field=models.CharField(blank=True, choices=[('1000', '1000'), ('2000', '2000'), ('3000', '3000'), ('4000', '4000'), ('5000', '5000'), ('6000', '6000'), ('7000', '7000'), ('8000', '8000'), ('9000', '9000'), ('10000', '10000')], max_length=50),
        ),
        migrations.AlterField(
            model_name='notebook',
            name='cpu_band',
            field=models.CharField(choices=[('INTEL', 'INTEL'), ('AMD', 'AMD'), ('APPLE', 'APPLE')], max_length=50),
        ),
        migrations.AlterField(
            model_name='notebook',
            name='cpu_gen',
            field=models.CharField(choices=[('CELERON', 'CELERON'), ('PENTIUM', 'PENTIUM'), ('I3', 'I3'), ('I5', 'I5'), ('I7', 'I7'), ('I9', 'I9'), ('RYZEN 3', 'RYZEN 3'), ('RYZEN 5', 'RYZEN 5'), ('RYZEN 7', 'RYZEN 7'), ('RYZEN 9', 'RYZEN 9'), ('M1', 'M1'), ('M1 Pro', 'M1 Pro'), ('M1 Max', 'M1 Max'), ('M2', 'M2'), ('M2 Pro', 'M2 Pro'), ('M2 Max', 'M2 Max'), ('M3', 'M3'), ('M3 Pro', 'M3 Pro'), ('M3 Max', 'M3 Max')], max_length=50),
        ),
        migrations.AlterField(
            model_name='notebook',
            name='rom',
            field=models.CharField(choices=[('128GB HHD', '128GB HHD'), ('256GB HHD', '256GB HHD'), ('512GB HHD', '512GB HHD'), ('1TB HHD', '1TB HHD'), ('2TB HHD', '2TB HHD'), ('3TB HHD', '3TB HHD'), ('4TB HHD', '4TB HHD'), ('5TB HHD', '5TB HHD'), ('128GB SSD', '128GB SSD'), ('256GB SSD', '256GB SSD'), ('512GB SSD', '512GB SSD'), ('1TB SSD', '1TB SSD'), ('2TB SSD', '2TB SSD'), ('3TB SSD', '3TB SSD'), ('4TB SSD', '4TB SSD'), ('5TB SSD', '5TB SSD')], max_length=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='warranty',
            field=models.CharField(choices=[('1สัปดาห์', '1สัปดาห์'), ('2สัปดาห์', '2สัปดาห์'), ('3สัปดาห์', '3สัปดาห์'), ('1เดือน', '1เดือน'), ('2เดือน', '2เดือน'), ('3เดือน', '3เดือน'), ('4เดือน', '4เดือน'), ('5เดือน', '5เดือน'), ('6เดือน', '6เดือน'), ('6เดือน', '7เดือน'), ('6เดือน', '8เดือน'), ('6เดือน', '9เดือน'), ('6เดือน', '10เดือน'), ('6เดือน', '11เดือน'), ('6เดือน', '12เดือน')], max_length=8, null=True),
        ),
    ]
