# Generated by Django 4.2.9 on 2024-05-06 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0022_alter_computer_mainboard_alter_computer_powersupply_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image1',
            field=models.ImageField(blank=True, upload_to='static/product_images/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image2',
            field=models.ImageField(blank=True, upload_to='static/product_images/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image3',
            field=models.ImageField(blank=True, upload_to='static/product_images/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='warranty',
            field=models.CharField(choices=[('1สัปดาห์', '1สัปดาห์'), ('2สัปดาห์', '2สัปดาห์'), ('3สัปดาห์', '3สัปดาห์'), ('1เดือน', '1เดือน'), ('2เดือน', '2เดือน'), ('3เดือน', '3เดือน'), ('4เดือน', '4เดือน'), ('5เดือน', '5เดือน'), ('6เดือน', '6เดือน'), ('7เดือน', '7เดือน'), ('8เดือน', '8เดือน'), ('9เดือน', '9เดือน'), ('10เดือน', '10เดือน'), ('11เดือน', '11เดือน'), ('1ปี', '1ปี')], max_length=8, null=True),
        ),
    ]
