# Generated by Django 4.2.9 on 2024-05-16 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0023_alter_product_image1_alter_product_image2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='computer',
            name='cpu_series',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='notebook',
            name='cpu_series',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.DeleteModel(
            name='Cpuseries',
        ),
    ]
