# Generated by Django 4.2.9 on 2024-05-22 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0027_product_has_detail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='computer',
            name='cpu_gen',
            field=models.CharField(choices=[('CELERON', 'CELERON'), ('PENTIUM', 'PENTIUM'), ('Core I3', 'Core I3'), ('Core I5', 'Core I5'), ('Core I7', 'Core I7'), ('Core I9', 'Core I9'), ('RYZEN 3', 'RYZEN 3'), ('RYZEN 5', 'RYZEN 5'), ('RYZEN 7', 'RYZEN 7'), ('RYZEN 9', 'RYZEN 9'), ('M1', 'M1'), ('M1 Pro', 'M1 Pro'), ('M1 Max', 'M1 Max'), ('M2', 'M2'), ('M2 Pro', 'M2 Pro'), ('M2 Max', 'M2 Max'), ('M3', 'M3'), ('M3 Pro', 'M3 Pro'), ('M3 Max', 'M3 Max')], max_length=50),
        ),
        migrations.AlterField(
            model_name='notebook',
            name='cpu_gen',
            field=models.CharField(choices=[('CELERON', 'CELERON'), ('PENTIUM', 'PENTIUM'), ('Core I3', 'Core I3'), ('Core I5', 'Core I5'), ('Core I7', 'Core I7'), ('Core I9', 'Core I9'), ('RYZEN 3', 'RYZEN 3'), ('RYZEN 5', 'RYZEN 5'), ('RYZEN 7', 'RYZEN 7'), ('RYZEN 9', 'RYZEN 9'), ('M1', 'M1'), ('M1 Pro', 'M1 Pro'), ('M1 Max', 'M1 Max'), ('M2', 'M2'), ('M2 Pro', 'M2 Pro'), ('M2 Max', 'M2 Max'), ('M3', 'M3'), ('M3 Pro', 'M3 Pro'), ('M3 Max', 'M3 Max')], max_length=50),
        ),
    ]
