# Generated by Django 4.2.9 on 2024-05-22 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0028_alter_computer_cpu_gen_alter_notebook_cpu_gen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notebook',
            name='camera',
            field=models.CharField(choices=[('ไม่มี', 'ไม่มี'), ('มี', 'มี')], max_length=50, null=True),
        ),
    ]
